filter:
    excluded_paths:
        - "api/tests/*"
        - "backend/tests/*"
        - "common/tests/*"
        - "frontend/tests/*"
        - "environments/*"
        - "vagrant/*"
        - "modules/users/migrations/*"
        - "modules/rbac/tests/*"
        - "modules/rbac/migrations/*"
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
#    external_code_coverage:
#    timeout: 600 # Timeout in seconds.
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
    php_loc:
        enabled: true
        excluded_dirs:
            - "vendor"
            - "environments"
            - "vagrant"
            - "api/tests"
            - "backend/tests"
            - "common/tests"
            - "frontend/tests"
            - "modules/rbac/tests"
            - "api/runtime"
            - "backend/runtime"
            - "console/runtime"
            - "frontend/runtime"
    # disable copy paste detector and similarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_cpd: false
    php_sim: false
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
