language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer self-update
  - composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer install --dev